server:
    port: 8082
    context-path: /boot
spring:
    datasource:
        name: mydb
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/openfree?useUnicode=true&characterEncoding=utf8
        username: mysql_dba
        password: MySql_DBA.110
        driver-class-name: com.mysql.jdbc.Driver
        minIdle: 1
        maxActive: 10
        initialSize: 1
        timeBetweenEvictionRunsMillis: 3000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 'ZTM' FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
    redis:
        host: localhost
        port: 6379
        timeout: 0
        pool:
            max-active: 8
            max-idle: 8
            max-wait: -1
            min-idle: 0
    thymeleaf:
        mode: HTML5
    freemarker:
      charset: UTF-8
    #session共享基于redis
    session:
      store-type: redis
    activemq:
      broker-url: tcp://127.0.0.1:61616
      user: admin
      password: 12356
mybatis:
    mapper-locations: classpath:mappers/**/*Mapper.xml
    type-aliases-package: org.lk.springboot.demo.domain.model
    config-location: classpath:mybatis-config.xml
pagehelper:
  auto-dialect: true
  reasonable: true